apiVersion: v1
kind: Service
metadata:
  labels:
    app: mytestapp
  name: mock-preview
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: mytestapp
  type: LoadBalancer
